name: Build & Publish to GHCR

on:
  push:
    branches: [ "main" ]
    tags: [ "v*.*.*" ]

permissions:
  contents: read
  packages: write

env:
  IMAGE_NAME: runpod-comfy-flux-ip

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      # Free up space so the big base image fits
      - name: Free disk space
        uses: easimon/maximize-build-space@v10
        with:
          remove-android: 'true'
          remove-dotnet: 'true'
          remove-haskell: 'true'
          remove-codeql: 'true'
          remove-docker-images: 'true'
          root-reserve-mb: 1024
          swap-size-mb: 1024

      - name: Assert Dockerfile exists
        run: |
          echo "WORKSPACE=$GITHUB_WORKSPACE"
          ls -la "$GITHUB_WORKSPACE"
          test -f "$GITHUB_WORKSPACE/Dockerfile" || (echo "🚨 Dockerfile NOT FOUND at repo root"; exit 99)

      - name: Log in to GHCR
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Extract metadata (tags, labels)
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: ghcr.io/${{ github.repository_owner }}/${{ env.IMAGE_NAME }}
          tags: |
            type=ref,event=branch
            type=sha
            type=semver,pattern={{version}},value=${{ github.ref_name }}

      - name: Set up Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build and push (linux/amd64)
        uses: docker/build-push-action@v6
        with:
          context: .
          file: ./Dockerfile
          platforms: linux/amd64
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
          sbom: false
          provenance: false
          cache-from: type=gha
          cache-to: type=gha,mode=max
